/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as RedirectRouteImport } from "./routes/redirect_"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as UpcomingIndexRouteImport } from "./routes/upcoming/index"
import { Route as TodayIndexRouteImport } from "./routes/today/index"
import { Route as CompletedIndexRouteImport } from "./routes/completed/index"
import { Route as ListListIdRouteImport } from "./routes/list/$listId"

const RedirectRoute = RedirectRouteImport.update({
  id: "/redirect_",
  path: "/redirect",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingIndexRoute = UpcomingIndexRouteImport.update({
  id: "/upcoming/",
  path: "/upcoming/",
  getParentRoute: () => rootRouteImport,
} as any)
const TodayIndexRoute = TodayIndexRouteImport.update({
  id: "/today/",
  path: "/today/",
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedIndexRoute = CompletedIndexRouteImport.update({
  id: "/completed/",
  path: "/completed/",
  getParentRoute: () => rootRouteImport,
} as any)
const ListListIdRoute = ListListIdRouteImport.update({
  id: "/list/$listId",
  path: "/list/$listId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/redirect": typeof RedirectRoute
  "/list/$listId": typeof ListListIdRoute
  "/completed": typeof CompletedIndexRoute
  "/today": typeof TodayIndexRoute
  "/upcoming": typeof UpcomingIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/redirect": typeof RedirectRoute
  "/list/$listId": typeof ListListIdRoute
  "/completed": typeof CompletedIndexRoute
  "/today": typeof TodayIndexRoute
  "/upcoming": typeof UpcomingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/redirect_": typeof RedirectRoute
  "/list/$listId": typeof ListListIdRoute
  "/completed/": typeof CompletedIndexRoute
  "/today/": typeof TodayIndexRoute
  "/upcoming/": typeof UpcomingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/redirect"
    | "/list/$listId"
    | "/completed"
    | "/today"
    | "/upcoming"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/about"
    | "/redirect"
    | "/list/$listId"
    | "/completed"
    | "/today"
    | "/upcoming"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/redirect_"
    | "/list/$listId"
    | "/completed/"
    | "/today/"
    | "/upcoming/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RedirectRoute: typeof RedirectRoute
  ListListIdRoute: typeof ListListIdRoute
  CompletedIndexRoute: typeof CompletedIndexRoute
  TodayIndexRoute: typeof TodayIndexRoute
  UpcomingIndexRoute: typeof UpcomingIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/redirect_": {
      id: "/redirect_"
      path: "/redirect"
      fullPath: "/redirect"
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/upcoming/": {
      id: "/upcoming/"
      path: "/upcoming"
      fullPath: "/upcoming"
      preLoaderRoute: typeof UpcomingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/today/": {
      id: "/today/"
      path: "/today"
      fullPath: "/today"
      preLoaderRoute: typeof TodayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/completed/": {
      id: "/completed/"
      path: "/completed"
      fullPath: "/completed"
      preLoaderRoute: typeof CompletedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/list/$listId": {
      id: "/list/$listId"
      path: "/list/$listId"
      fullPath: "/list/$listId"
      preLoaderRoute: typeof ListListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RedirectRoute: RedirectRoute,
  ListListIdRoute: ListListIdRoute,
  CompletedIndexRoute: CompletedIndexRoute,
  TodayIndexRoute: TodayIndexRoute,
  UpcomingIndexRoute: UpcomingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
