# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - main
      - develop
      - feature/**
      - bugfix/**
      - hotfix/**
      - release/**

env:
  DOTNET_VERSION: "8.0.x"
  PROJECT_PATH: "./api"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies
        shell: bash
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet restore
      - name: Build
        shell: bash
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet build --no-restore
      - name: Test
        shell: bash
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet test --no-build --verbosity normal
